<table class="table table-striped" id="table">
    <thead>
        <tr style="text-align: center;">
            <th scope="col">Nome Completo</th>
            <th scope="col">Nome Usuário</th>
            <th scope="col">Senha</th>
            <th scope="col">Telefone</th>
            <th scope="col">E-mail</th>
            <th scope="col">Idade</th>
            <th scope="col">Cidade</th>
            <th scope="col">Estado</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>